// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/ratings/service.proto

package ratings

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RatingsService_SubmitRating_FullMethodName = "/ratings.RatingsService/SubmitRating"
)

// RatingsServiceClient is the client API for RatingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RatingsServiceClient interface {
	SubmitRating(ctx context.Context, in *SubmitRatingRequest, opts ...grpc.CallOption) (*SubmitRatingResponse, error)
}

type ratingsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRatingsServiceClient(cc grpc.ClientConnInterface) RatingsServiceClient {
	return &ratingsServiceClient{cc}
}

func (c *ratingsServiceClient) SubmitRating(ctx context.Context, in *SubmitRatingRequest, opts ...grpc.CallOption) (*SubmitRatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitRatingResponse)
	err := c.cc.Invoke(ctx, RatingsService_SubmitRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RatingsServiceServer is the server API for RatingsService service.
// All implementations must embed UnimplementedRatingsServiceServer
// for forward compatibility.
type RatingsServiceServer interface {
	SubmitRating(context.Context, *SubmitRatingRequest) (*SubmitRatingResponse, error)
	mustEmbedUnimplementedRatingsServiceServer()
}

// UnimplementedRatingsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRatingsServiceServer struct{}

func (UnimplementedRatingsServiceServer) SubmitRating(context.Context, *SubmitRatingRequest) (*SubmitRatingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitRating not implemented")
}
func (UnimplementedRatingsServiceServer) mustEmbedUnimplementedRatingsServiceServer() {}
func (UnimplementedRatingsServiceServer) testEmbeddedByValue()                        {}

// UnsafeRatingsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RatingsServiceServer will
// result in compilation errors.
type UnsafeRatingsServiceServer interface {
	mustEmbedUnimplementedRatingsServiceServer()
}

func RegisterRatingsServiceServer(s grpc.ServiceRegistrar, srv RatingsServiceServer) {
	// If the following call pancis, it indicates UnimplementedRatingsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RatingsService_ServiceDesc, srv)
}

func _RatingsService_SubmitRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingsServiceServer).SubmitRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatingsService_SubmitRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingsServiceServer).SubmitRating(ctx, req.(*SubmitRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RatingsService_ServiceDesc is the grpc.ServiceDesc for RatingsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RatingsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ratings.RatingsService",
	HandlerType: (*RatingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitRating",
			Handler:    _RatingsService_SubmitRating_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/ratings/service.proto",
}
