// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: api/ratings/service.proto

package ratings

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	FoodItem      string                 `protobuf:"bytes,2,opt,name=food_item,json=foodItem,proto3" json:"food_item,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRatingRequest) Reset() {
	*x = SubmitRatingRequest{}
	mi := &file_api_ratings_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRatingRequest) ProtoMessage() {}

func (x *SubmitRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ratings_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRatingRequest.ProtoReflect.Descriptor instead.
func (*SubmitRatingRequest) Descriptor() ([]byte, []int) {
	return file_api_ratings_service_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitRatingRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SubmitRatingRequest) GetFoodItem() string {
	if x != nil {
		return x.FoodItem
	}
	return ""
}

func (x *SubmitRatingRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type SubmitRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRatingResponse) Reset() {
	*x = SubmitRatingResponse{}
	mi := &file_api_ratings_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRatingResponse) ProtoMessage() {}

func (x *SubmitRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ratings_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRatingResponse.ProtoReflect.Descriptor instead.
func (*SubmitRatingResponse) Descriptor() ([]byte, []int) {
	return file_api_ratings_service_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitRatingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_ratings_service_proto protoreflect.FileDescriptor

var file_api_ratings_service_proto_rawDesc = string([]byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x22, 0x65, 0x0a, 0x13, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x6f, 0x6f, 0x64, 0x5f, 0x69,
	0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x6f, 0x6f, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x2e, 0x0a, 0x14, 0x53,
	0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x5f, 0x0a, 0x0e, 0x52,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a,
	0x0c, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x2e,
	0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x72, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3b, 0x5a, 0x39,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x65, 0x73, 0x74, 0x72,
	0x6f, 0x79, 0x65, 0x72, 0x41, 0x6c, 0x70, 0x68, 0x61, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65,
	0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_api_ratings_service_proto_rawDescOnce sync.Once
	file_api_ratings_service_proto_rawDescData []byte
)

func file_api_ratings_service_proto_rawDescGZIP() []byte {
	file_api_ratings_service_proto_rawDescOnce.Do(func() {
		file_api_ratings_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ratings_service_proto_rawDesc), len(file_api_ratings_service_proto_rawDesc)))
	})
	return file_api_ratings_service_proto_rawDescData
}

var file_api_ratings_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_ratings_service_proto_goTypes = []any{
	(*SubmitRatingRequest)(nil),  // 0: ratings.SubmitRatingRequest
	(*SubmitRatingResponse)(nil), // 1: ratings.SubmitRatingResponse
}
var file_api_ratings_service_proto_depIdxs = []int32{
	0, // 0: ratings.RatingsService.SubmitRating:input_type -> ratings.SubmitRatingRequest
	1, // 1: ratings.RatingsService.SubmitRating:output_type -> ratings.SubmitRatingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_ratings_service_proto_init() }
func file_api_ratings_service_proto_init() {
	if File_api_ratings_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ratings_service_proto_rawDesc), len(file_api_ratings_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ratings_service_proto_goTypes,
		DependencyIndexes: file_api_ratings_service_proto_depIdxs,
		MessageInfos:      file_api_ratings_service_proto_msgTypes,
	}.Build()
	File_api_ratings_service_proto = out.File
	file_api_ratings_service_proto_goTypes = nil
	file_api_ratings_service_proto_depIdxs = nil
}
