// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: api/customer/service.proto

package customer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cuisine       string                 `protobuf:"bytes,1,opt,name=cuisine,proto3" json:"cuisine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuRequest) Reset() {
	*x = GetMenuRequest{}
	mi := &file_api_customer_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuRequest) ProtoMessage() {}

func (x *GetMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuRequest.ProtoReflect.Descriptor instead.
func (*GetMenuRequest) Descriptor() ([]byte, []int) {
	return file_api_customer_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetMenuRequest) GetCuisine() string {
	if x != nil {
		return x.Cuisine
	}
	return ""
}

type GetMenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FoodItems     []string               `protobuf:"bytes,1,rep,name=food_items,json=foodItems,proto3" json:"food_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuResponse) Reset() {
	*x = GetMenuResponse{}
	mi := &file_api_customer_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuResponse) ProtoMessage() {}

func (x *GetMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuResponse.ProtoReflect.Descriptor instead.
func (*GetMenuResponse) Descriptor() ([]byte, []int) {
	return file_api_customer_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetMenuResponse) GetFoodItems() []string {
	if x != nil {
		return x.FoodItems
	}
	return nil
}

type PlaceFoodOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FoodItem      string                 `protobuf:"bytes,1,opt,name=food_item,json=foodItem,proto3" json:"food_item,omitempty"`
	Cuisine       string                 `protobuf:"bytes,2,opt,name=cuisine,proto3" json:"cuisine,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceFoodOrderRequest) Reset() {
	*x = PlaceFoodOrderRequest{}
	mi := &file_api_customer_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceFoodOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceFoodOrderRequest) ProtoMessage() {}

func (x *PlaceFoodOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceFoodOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceFoodOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_customer_service_proto_rawDescGZIP(), []int{2}
}

func (x *PlaceFoodOrderRequest) GetFoodItem() string {
	if x != nil {
		return x.FoodItem
	}
	return ""
}

func (x *PlaceFoodOrderRequest) GetCuisine() string {
	if x != nil {
		return x.Cuisine
	}
	return ""
}

func (x *PlaceFoodOrderRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type PlaceFoodOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceFoodOrderResponse) Reset() {
	*x = PlaceFoodOrderResponse{}
	mi := &file_api_customer_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceFoodOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceFoodOrderResponse) ProtoMessage() {}

func (x *PlaceFoodOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceFoodOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceFoodOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_customer_service_proto_rawDescGZIP(), []int{3}
}

func (x *PlaceFoodOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PlaceFoodOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReviewFoodItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	FoodItem      string                 `protobuf:"bytes,2,opt,name=food_item,json=foodItem,proto3" json:"food_item,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewFoodItemRequest) Reset() {
	*x = ReviewFoodItemRequest{}
	mi := &file_api_customer_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewFoodItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewFoodItemRequest) ProtoMessage() {}

func (x *ReviewFoodItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewFoodItemRequest.ProtoReflect.Descriptor instead.
func (*ReviewFoodItemRequest) Descriptor() ([]byte, []int) {
	return file_api_customer_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReviewFoodItemRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReviewFoodItemRequest) GetFoodItem() string {
	if x != nil {
		return x.FoodItem
	}
	return ""
}

func (x *ReviewFoodItemRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type ReviewFoodItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      string                 `protobuf:"bytes,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewFoodItemResponse) Reset() {
	*x = ReviewFoodItemResponse{}
	mi := &file_api_customer_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewFoodItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewFoodItemResponse) ProtoMessage() {}

func (x *ReviewFoodItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewFoodItemResponse.ProtoReflect.Descriptor instead.
func (*ReviewFoodItemResponse) Descriptor() ([]byte, []int) {
	return file_api_customer_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReviewFoodItemResponse) GetReviewId() string {
	if x != nil {
		return x.ReviewId
	}
	return ""
}

func (x *ReviewFoodItemResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_customer_service_proto protoreflect.FileDescriptor

var file_api_customer_service_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e,
	0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x69, 0x73,
	0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x75, 0x69, 0x73, 0x69,
	0x6e, 0x65, 0x22, 0x30, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x6f, 0x6f, 0x64, 0x5f, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6f, 0x6f, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x6a, 0x0a, 0x15, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x46, 0x6f, 0x6f,
	0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x66, 0x6f, 0x6f, 0x64, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x6f, 0x6f, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75,
	0x69, 0x73, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x75, 0x69,
	0x73, 0x69, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x22, 0x4b, 0x0a, 0x16, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x46, 0x6f, 0x6f, 0x64, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x67, 0x0a,
	0x15, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x46, 0x6f, 0x6f, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x6f, 0x6f, 0x64, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x6f, 0x6f, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x4d, 0x0a, 0x16, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x46, 0x6f, 0x6f, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x81, 0x02, 0x0a, 0x0f, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x6e, 0x75, 0x12, 0x18, 0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e,
	0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x0e, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x46, 0x6f, 0x6f, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1f, 0x2e,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x46, 0x6f,
	0x6f, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x46,
	0x6f, 0x6f, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x55, 0x0a, 0x0e, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x46, 0x6f, 0x6f, 0x64,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x1f, 0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e,
	0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x46, 0x6f, 0x6f, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x46, 0x6f, 0x6f, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x65,
	0x72, 0x41, 0x6c, 0x70, 0x68, 0x61, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2d, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_api_customer_service_proto_rawDescOnce sync.Once
	file_api_customer_service_proto_rawDescData []byte
)

func file_api_customer_service_proto_rawDescGZIP() []byte {
	file_api_customer_service_proto_rawDescOnce.Do(func() {
		file_api_customer_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_customer_service_proto_rawDesc), len(file_api_customer_service_proto_rawDesc)))
	})
	return file_api_customer_service_proto_rawDescData
}

var file_api_customer_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_customer_service_proto_goTypes = []any{
	(*GetMenuRequest)(nil),         // 0: customer.GetMenuRequest
	(*GetMenuResponse)(nil),        // 1: customer.GetMenuResponse
	(*PlaceFoodOrderRequest)(nil),  // 2: customer.PlaceFoodOrderRequest
	(*PlaceFoodOrderResponse)(nil), // 3: customer.PlaceFoodOrderResponse
	(*ReviewFoodItemRequest)(nil),  // 4: customer.ReviewFoodItemRequest
	(*ReviewFoodItemResponse)(nil), // 5: customer.ReviewFoodItemResponse
}
var file_api_customer_service_proto_depIdxs = []int32{
	0, // 0: customer.CustomerService.GetMenu:input_type -> customer.GetMenuRequest
	2, // 1: customer.CustomerService.PlaceFoodOrder:input_type -> customer.PlaceFoodOrderRequest
	4, // 2: customer.CustomerService.ReviewFoodItem:input_type -> customer.ReviewFoodItemRequest
	1, // 3: customer.CustomerService.GetMenu:output_type -> customer.GetMenuResponse
	3, // 4: customer.CustomerService.PlaceFoodOrder:output_type -> customer.PlaceFoodOrderResponse
	5, // 5: customer.CustomerService.ReviewFoodItem:output_type -> customer.ReviewFoodItemResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_customer_service_proto_init() }
func file_api_customer_service_proto_init() {
	if File_api_customer_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_customer_service_proto_rawDesc), len(file_api_customer_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_customer_service_proto_goTypes,
		DependencyIndexes: file_api_customer_service_proto_depIdxs,
		MessageInfos:      file_api_customer_service_proto_msgTypes,
	}.Build()
	File_api_customer_service_proto = out.File
	file_api_customer_service_proto_goTypes = nil
	file_api_customer_service_proto_depIdxs = nil
}
